- name: Install unzip
  become: yes
  apt:
    name: unzip
    state: present

- name: Install python3
  become: yes
  apt:
    name: python3
    state: present

- name: Install pip
  become: yes
  apt:
    name: python3-pip
    state: present

- name: Install github3.py
  pip:
    name: github3.py

- name: Creates `pb` directory
  file:
    mode: 0755
    path: "{{ pocketbase_dir }}"
    state: directory
    recurse: yes

- name: Get latest pocketbase release
  community.general.github_release:
    token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') }}"
    user: pocketbase
    repo: pocketbase
    action: latest_release
  register: pocketbase_release

- name: Unzip pocketbase
  unarchive:
    src: "https://github.com/pocketbase/pocketbase/releases/download/{{ pocketbase_release['tag'] }}/pocketbase_{{ pocketbase_release['tag'] | regex_replace('^v','') }}_linux_amd64.zip"
    dest: "{{ pocketbase_dir }}"
    creates: "{{ pocketbase_dir }}/pocketbase"
    remote_src: yes

- name: Copy `pocketbase.service`
  copy:
    src: pocketbase.service
    mode: 0644
    dest: /lib/systemd/system/pocketbase.service

- name: Re-start `pocketbase.service`
  systemd:
    name: pocketbase.service
    state: restarted
    enabled: yes

- name: Get `pb_data` disk ID
  find: 
    paths: /dev/disk/by-id/
    file_type: "link"
  register: disk_id

# - https://www.garrettbland.com/posts/adding-volume-storage-to-digital-ocean-droplet/
- name: Add `pb_data` disk to `/etc/fstab`
  lineinfile:
    path: /etc/fstab
    line: "{{ disk_id.files[0].path }} {{ pocketbase_dir }}/pb_data ext4 defaults,nofail,discard 0 0"
  when: disk_id.files[0] is defined

- name: Mount `pb_data` disk
  command:
    cmd: "/usr/bin/mount -a"
  when: disk_id.files[0] is defined

